# Generated by Django 4.2.30 on 2026-08-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('missing_data', models.BooleanField(default=False)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
